FROM node:alpine as builder

WORKDIR /usr/podcase
COPY ./ /usr/podcase/

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/podcase/build/ /usr/share/nginx/html
